services:
  laravel_app:
    image: php:8.2-fpm   # Usando PHP 8.0 com FPM
    container_name: laravel_app
    volumes:
      - .:/var/www/html   # Mapeando o diretório local para o container
    ports:
      - 8082:8000         # Expondo a porta 8000
    networks:
      - app-network
    depends_on:
      - db                # O Laravel vai depender do serviço db (MySQL)

  db:
    image: mysql:8.0       # Usando a imagem do MySQL 8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
